Iter13
sanbright/go_shortener pull request #5
Opened 2024-08-13 14:13 UTC by sanbright

2024-08-18 22:10 UTC, vokinneberg requested changes
Ура, первое ревью третьего спринта! 🎉 В этом спринте наше приложение стало еще сложнее, добавился новый слой БД 💪 Мне хотелось бы добавить несколько комментариев относительно твоего кода и сделать несколько предложений по улучшению. 🤓

**Сильные стороны твоего PR:**

1. Код функционален и корректен! 🚀
2. Ты консистентно встроил функционал в структуру существующего приложения. 👍
3. Ты сделал рефакторинг некоторых компонентов, и твой код сохранил лаконичность. 🚀

**На что я бы рекомендовал обратить внимание и что можно улучшить:**

1. Согласно постановке задачи *изменение в базе можно выполнять в рамках одной транзакции или одного запроса*. Стоит реализовать это требование.
2. В `PostBathShortLinkHandler` не стоит игнорировать ошибку в момент добавления URL, а также стоит добавить проверку конфликта с существующим URL, как это сделано в `postAPIShortLinkHandler.go`.
3. Было бы здорово реализовать проверку кейса с конфликтом с существующим URL.

2024-08-18 22:10 UTC, vokinneberg commented on internal/app/handler/getPingHandler.go
> +	db, err := sqlx.Connect("postgres", handler.Config.DatabaseDSN)
Я бы рекомендовал вынести инициализацию БД в метод `main` и передавать созданный инстанс, как зависимость в остальные компоненты, которые его используют.

2024-08-18 22:10 UTC, vokinneberg commented on internal/app/handler/postBathShortLinkHandler.go
> +type PostBathShortLinkHandler struct {
Здесь вероятно опечатка в названии?
```suggestion
type PostBatсhShortLinkHandler struct {
```

2024-08-18 22:10 UTC, vokinneberg commented on internal/app/handler/postBathShortLinkHandler.go
> +		shortLinkEntity, _ := handler.service.Add(element.OriginalURL)
Согласно постановке задачи _изменение в базе можно выполнять в рамках одной транзакции или одного запроса_. Насколько я понимаю метод `Add()` добавляет URL по одному? Стоит реализовать это требование.

2024-08-18 22:10 UTC, vokinneberg commented on internal/app/handler/postBathShortLinkHandler.go
> +		shortLinkEntity, _ := handler.service.Add(element.OriginalURL)
Не стоит игнорировать ошибку, а так же стоит добавить проверку конфликта c существующим URL, как это сделано в `postAPIShortLinkHandler.go`.

2024-08-18 22:10 UTC, vokinneberg commented on internal/app/handler/postBathShortLinkHandler_test.go
> +func TestPostBathShortLinkHandler_Handle(t *testing.T) {
Было бы здорово реализовать проверку кейса с конфликтом с существующим URL.

2024-08-18 22:10 UTC, vokinneberg commented on internal/app/repository/repositoryResolver.go
> +`
Можно определить литерах с sql  кодом, как const.
```suggestion
const schema = `
CREATE TABLE IF NOT EXISTS short_link (
	"uuid" UUID NOT NULL,
	"short_link" VARCHAR(10) NOT NULL,
	"url" TEXT NOT NULL,
	PRIMARY KEY ("uuid")
);

CREATE UNIQUE INDEX IF NOT EXISTS short_link__uniq ON short_link (short_link);
CREATE UNIQUE INDEX IF NOT EXISTS url__uniq ON short_link (url);
`
```

 Так же мне кажется правильнее было бы определить схему в  DB Repository, так мы скроем детали реализации и будем соблюдать принцип single responsibility.

2024-08-22 22:10 UTC, sanbright commented on internal/app/handler/getPingHandler.go
> +	db, err := sqlx.Connect("postgres", handler.Config.DatabaseDSN)
почему-то у меня локально при использовании одного инстанса соединения с субд, при выполнении запроса ping в момент остановки службы субд, ошибка норм выдавалась, но при запуске субд без перезапуска приложения метод ping не начинал работать.

Временно оставил реализацию как есть, может позже успею поправить

2024-08-24 04:11 UTC, vokinneberg approved these changes
Поздравляю с успешным завершением третьего спринта!  🎉  Отличная работа! 🚀

2024-08-24 04:11 UTC, vokinneberg commented on internal/app/repository/shortLinkDBRepository.go
> +	tx, err := repo.db.Begin()
👍

2024-08-30 18:28 UTC, merged